### ISSUE TITLE
Inconsistent download reporting

### ISSUE THREAD

**Issue by ParsonsGlory** [Nezreka/SoulSync#81]
First up amazing work - super impressed!

I've set it up in docker and loaded a small playlist from Spotify to test it.

- soulsync correctly identified that I already had some tracks from the playlist in my plex media library 
- soulsync queried soulseek for the missing 9 tracks and immediately reported the download for some as failed and others as downloading. Eventually  it reported 6 tracks as downloaded and three tracks were transferred to the wish list
- in fact Soulseek downloaded 8 tracks and reported one track as completed but errored
- in the download folder  8 tracks were present and only the completed but errored track was missing
- no completed tracks were transferred from the download folder to the music library

Looking at the log soulseek was refusing many api requests "HTTP 429 (too many requests) - only one concurrent operation is permitted". Possibly the refused requests triggers soulsync to mark them failed?

There was no information in the log about why the transfer to the music library didn't run - however the files in the download folder were in folders variously named after the artist or the album and I'm not sure how the transfer operation will sort that out.

The log reports many (100 or so) saves of the M3U playlist file.

So a few questions:
- can soulseek be configured to handle concurrent requests or can soulsync be configured to hold requests as pending rather than overload soulseek and report the request as failed ( if that is in fact what is happening)?
- is the initial report of failure causing the files which were in fact downloaded to be transferred to the wish list when in fact they were downloaded eventually?
- how do I turn the debug log on so I can problem solve the transfer of downloaded files to the music library

**Comment by Nezreka** [comment]
Thank you!

The issue is that your Transfer folder (music library) isn't mounted in Docker. Add this to your 
  docker-compose.yml:

  volumes:
    - ./downloads:/app/downloads
    - /path/to/your/plex/music:/app/Transfer:rw  # Your actual Plex music path

Let me know if this helps at all.  

In regard to slskd reporting too many calls, I'll take a look at that, it shouldn't be happening with the current rate limiting. 

I'm adding an easier way to change the debug log level and will push in an update soon.

**Comment by ParsonsGlory** [comment]
I'm sure I haven't got the volumes right in the compose. This is what I have. My plex music folder is at /mnt/data/media/music.
What should I put in matched transfer directory in download settings in soulsync - app/Transfer?
volumes:
      - /home/myname/apps/soulsync/config:/app/config
      - /home/myname/apps/soulsync/database:/app/database
      - /home/myname/apps/soulsync/logs:/app/logs
      - /mnt/data/slskd/downloads:/app/downloads
      - /mnt/data/media/music:/app/Transfer:rw

**Comment by ParsonsGlory** [comment]
Actually I dont have the database volume. Including that caused problems so I removed it.

**Comment by ParsonsGlory** [comment]
Here is my full compose. Unless I have done something wrong this doesn't work on linux docker.

When I run soulsync there are obvious communication problems between soulsync and slskd. I synced a 4 track spotify playlist. It immediately reported all 4 failed but  no searches had been made slskd. The wish list ran later and three tracks downloaded but soulsync says only 2 have and reports the 3rd as failed. There have been no searches for the 4th track and none of the files have transferred to the music library. There are no errors in the log.

  soulsync:
   image: boulderbadgedad/soulsync:latest
   container_name: soulsync-webui
   environment:
    - PUID=1000
    - PGID=1000 
    - UMASK=022
    - SOULSYNC_CONFIG_PATH=/app/config/config.json
    - TZ=Pacific/Auckland
   ports:
    - 8008:8008
    - 8888:8888
    - 8889:8889
   volumes:
    - /home/myname/apps/soulsync/config:/app/config
    # - soulsync_database:/app/database
    - /home/myname/apps/soulsync/logs:/app/logs
    - /mnt/data/slskd/downloads:/app/downloads
    - /mnt/data/media/music:/app/Transfer:rw
   restart: unless-stopped

**Comment by Nezreka** [comment]
Your docker-compose is missing critical configuration. 

  Fixed docker-compose.yml

  soulsync:
    image: boulderbadgedad/soulsync:latest
    container_name: soulsync-webui
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Pacific/Auckland
    ports:
      - 8008:8008
      - 8888:8888
      - 8889:8889
    volumes:
      - /home/myname/apps/soulsync/config:/app/config
      - soulsync_database:/app/database  # Required - uncomment!
      - /home/myname/apps/soulsync/logs:/app/logs
      - /mnt/data/slskd/downloads:/app/downloads
      - /mnt/data/media/music:/app/Transfer:rw
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Required for slskd!
    restart: unless-stopped

  volumes:
    soulsync_database:
      driver: local

  SoulSync Settings

  - slskd URL: http://host.docker.internal:5030
  - Download Path: /app/downloads
  - Transfer Path: /app/Transfer
  - Log Level: DEBUG (for troubleshooting)


  Missing extra_hosts / Database commented out 

  Quick Test

  docker-compose down && docker-compose up -d
  docker exec soulsync-webui curl http://host.docker.internal:5030/api/v0/application
  Should return JSON - if it fails, slskd isn't reachable

  Try this and let me know if searches start working

**Comment by ParsonsGlory** [comment]
Thanks. Super helpful and now I know that I have it setup correctly. 
It's still not working properly though and looking at the logs I think my slskd setup which is the problem. Soulsync sets the download running but doesn't appear to know that the download has occurred so the dashboard doesn't update properly and the transfer never runs. Soulsync app downloads is pointed to the download directory of slskd but something isn't right there. I'll do some more investigating....

**Comment by ParsonsGlory** [comment]
Nope. Doesn't appear to be a slskd issue. I synced a 16 track playlist from utube music. 8 downloaded and 8 were transferred to the wishlist. Nothing happened to the folders/files in slskd download directory. No tagging nor transfer to the music library. No error in the log. Completed downloads are cleared from slskd and an incremental database update takes place and thats all - what should happen when downloads are completed - some form of post-processing?

**Comment by ParsonsGlory** [comment]
Found the transfer guide and sorted my problems working through that! Sync seems to work well - just need to fiddle with the file template and I'll try syncing one of my big templates. The search function just transfers the album into the music folder without file organisation - is that how its meant to work?

**Comment by Nezreka** [comment]
Nice I'm glad you got it up and running! Yes you were right that was a bug with the manual searching. The newest repo and image has this fixed and is consistent with a normal matching process with lrc, naming and tags.

**Comment by ParsonsGlory** [comment]
Great search works well now. A couple of other things I've noticed after running it for a while.

-  the wishlist scheduler doesn't work properly. Maybe it needs the webui open? It only runs very spasmodically - up to 12 hours with no activity? Sometimes the timer information is displayed and other times nothing.
- can you make the wishlist downloading screen resizable? On a laptop its impossible to see the track analysis and download pane which is pretty frustrating.

**Comment by Nezreka** [comment]
Excellent! Yes, I just pushed a new image / repo update that will resolve the wishlist issue and that shouldn't happen anymore. Also, the sizing of the wishlist should now be resolved. Soon I will be putting in some real effort for mobile view.

**Comment by ParsonsGlory** [comment]
Ok new image partially resolved the wishlist issue. It ran at 30 minute intervals for a while then stopped. Looking at the log it's stalled. I can't see a permission issue as lots of files have been successfully transferred. This may have been the issue all along as I've noticed that sometimes a file is downloaded but not transferred.
2025-12-17 06:17:49 - newmusic - INFO - Processing simple download (no metadata enhancement): /app/downloads/xxxx/xxx.mp3

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/shutil.py", line 853, in move

    os.rename(src, real_dst)

OSError: [Errno 18] Invalid cross-device link: '/app/downloads/xxxx/xxx.mp3' -> '/app/Transfer/xxxx/xxx.mp3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/app/web_server.py", line 7396, in _post_process_matched_download

    shutil.move(str(file_path), str(destination))

  File "/usr/local/lib/python3.11/shutil.py", line 873, in move

    copy_function(src, real_dst)

  File "/usr/local/lib/python3.11/shutil.py", line 449, in copy2

    copystat(src, dst, follow_symlinks=follow_symlinks)

  File "/usr/local/lib/python3.11/shutil.py", line 380, in copystat

    lookup("utime")(dst, ns=(st.st_atime_ns, st.st_mtime_ns),

PermissionError: [Errno 1] Operation not permitted

**Comment by Nezreka** [comment]
just pushed a fix for the cross-device transfer issue. the problem is /app/downloads and /app/Transfer are on     
 different filesystems (different volume types in docker), so when Python tries to move files it fails on
 metadata preservation.

pull the latest docker image and it should resolve this problem

**Comment by ParsonsGlory** [comment]
I think that last fix stuffed up the import from search function. Now it just transfers the files as downloaded by slskd - no tagging and placing in artist folder which worked before.
