### ISSUE TITLE
Spotify callback error behind reverse proxy

### ISSUE THREAD

**Issue by redbeardymcgee** [Nezreka/SoulSync#94]
```
Dec 27 13:53:17 perseus soulsync[233136]: 🎵 Spotify callback received: /
Dec 27 13:53:17 perseus soulsync[233136]: 🔴 Spotify OAuth error: Unknown error
Dec 27 13:53:17 perseus soulsync[233136]: 🔴 Full Spotify callback URL: /
Dec 27 13:53:17 perseus soulsync[233136]: 🔴 All query params: {}
Dec 27 13:53:17 perseus soulsync[233136]: 🔴 Spurious Spotify callback without code or error - ignoring
```

This was working just the other day, and now fails. Nothing seems broken in my developer dashboard, and connection test in soulsync returns success.

**Comment by Nezreka** [comment]
I'll be home from vacation in a couple days and will get this resolved.

**Comment by Nezreka** [comment]
This is odd. I just want to verify a couple things:

Is your spotify callback url in the spotify dashboard as well as the url in soulsync set to 

'http://127.0.0.1:8888/callback'?

**Comment by redbeardymcgee** [comment]
No, I have been experimenting with ways to use my reverse proxy to reach these callbacks since you implemented the ability to change the callback url. Changing the url is an accepted configuration, but it doesn't appear to work correctly.

**Comment by redbeardymcgee** [comment]
It appears that resetting the callback to default enables soulsync to work again.

**Comment by redbeardymcgee** [comment]
I take it back. The same error is still occurring.

**Comment by Venorrak** [comment]
I had this error, and I just didn't notice that I had to save the settings after setting the cliend id and secret before clicking on "authenticate". Now I must say that spotify updated their api and the callback route has to be https in order for it to work

**Comment by redbeardymcgee** [comment]
My settings are correctly configured and saved, so there is some other underlying problem. Unfortunately, whatever the issue is, it is not logged for review.

**Comment by Nezreka** [comment]
I have just pushed a new update to the repo that should solve this issue. docker image will be live shortly

**Comment by redbeardymcgee** [comment]
I appreciate you taking the time to work on this. I am still facing the error, and do not understand what changes, if any, I should be making to accommodate the new version. The commit message does not clarify, and the release notes do not mention it at all, nor does the readme.

**Comment by redbeardymcgee** [comment]
In addition, SoulSync has spammed my logs with 45GB of data. I do not have debug logging enabled anywhere that I can find at this time but it is making millions of duplicate log lines such as the following:

```
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_08_Go Hard Everyday.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_03_Head Money Trees Clothes.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_04_If You Know You Know.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_02_RN Check.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_11_It's Been A Minute.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: JamesTran::Wiz Khalifa_Khaotic_10_Wit My Twin.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: jimmybreeze::06 - I Put That Shit On.flac
Jan 30 12:30:18 perseus soulsync[3757654]:    Available keys: ['arvp::01 - Always Like This.flac', 'arvp::01 - Brazil.flac', 'Alexicario::Flyleaf - Set Me on Fire.flac']...
Jan 30 12:30:18 perseus soulsync[3757654]: ⚠️ [Context Lookup] No context found for key: jimmybreeze::01 - Intro.flac

```

This will repeat hundreds of times a minute, but there is no clarity as to what the log means or how I may try to resolve the warnings. It's very noisy and makes actually using the logs for debugging impossible, on top of filling up my disk and endangering my system of becoming unbootable.

**Comment by Nezreka** [comment]
Sorry about that logging issue, that's absurd. Going to cap it to log the last 24 hours only.  I'll dive into this issue more today. Reverse proxy is something I need to understand better

**Comment by redbeardymcgee** [comment]
I wish I could do more to help, but the script.js file feels totally unapproachable at 34k lines lol

**Comment by HVR88** [comment]
You should really consider dropping Spotify API integration if they keep reducing the functionality for indy devs. After their very public fiasco last month, new users can't even get API access at all - at least it told me applications were closed when I tried.

**Comment by Nezreka** [comment]
Yeah its a incredibly lame :( But I did implement full itunes metadata support to replace it. It will prefer spotify if it is available though.

**Comment by jarodsmk** [comment]
> You should really consider dropping Spotify API integration if they keep reducing the functionality for indy devs. After their very public fiasco last month, new users can't even get API access at all - at least it told me applications were closed when I tried.



> Yeah its a incredibly lame :( But I did implement full itunes metadata support to replace it. It will prefer spotify if it is available though.


I did manage to create an application and authenticate it in the last few days - 

My experience however is the artist search screen never returns any album/single results. Checking the logs, looks like I'm being rate limited by the Spotify API:

```
🎤 Fetching discography for artist: {artist ID} (name: {artist Name}, spotify: True)
100.81.41.100 - - [25/Feb/2026 22:24:24] "POST /api/watchlist/check HTTP/1.1" 200 -
Your application has reached a rate/request limit. Retry will occur after: 20751 s
```

Waited a day to see if it would clear, though seems persistant.

Edit: Sticking to the default Apple Music metadata source fixes the issue I encountered, but sharing the same sentiment as above, Spotify sucks.

**Comment by HVR88** [comment]
WOW 6 hour wait after rate limit. That's pretty much DOA = useless.

**Comment by Nezreka** [comment]
Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet

**Comment by jarodsmk** [comment]
> Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet

Installed SoulSync a day ago using `boulderbadgedad/soulsync:latest` - I see there's an update since, so benefit-of-the-doubt, will update and revert

**Comment by Nezreka** [comment]
What were you doing when you were rate limited?

**Comment by HVR88** [comment]
> Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet

how many queries per second/minute/whatever their period is?

I'm working on something right now and any extra providers I can support, I'll do so, within reason and if they have something to offer.

**Comment by Nezreka** [comment]
Spotify: 350ms between calls (~171/min), under Spotify's ~180/min limit. Exponential backoff on 429s (3s, 6s, 12s...).

**Comment by Nezreka** [comment]
> > Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet
> 
> how many queries per second/minute/whatever their period is?
> 
> I'm working on something right now and any extra providers I can support, I'll do so, within reason and if they have something to offer.

Curious, what are you building?

**Comment by Nezreka** [comment]
Wait this is it: https://github.com/HVR88/Limbo_Bridge_DEV?

How much experience do you have with p2p decentralized connections? I think we have similar ideas but executing differently :)

https://github.com/QuixThe2nd/Hydrabase

**Comment by Nezreka** [comment]
> > Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet
> 
> Installed SoulSync a day ago using `boulderbadgedad/soulsync:latest` - I see there's an update since, so benefit-of-the-doubt, will update and revert

How did the test go?

**Comment by redbeardymcgee** [comment]
It is not clear that the issue I reported is rate limiting at this time.

**Comment by Nezreka** [comment]
Are you still having the same problem? And this is directly related to reverse proxy?

**Comment by Nezreka** [comment]
hey so looking at your logs, the callback is hitting / with zero query params — spotify is redirecting but your reverse proxy is stripping the /callback path and the query string before it reaches soulsync. that's why it works when you go direct with
http://127.0.0.1:8888/callback.

also worth noting spotify now requires HTTPS on callback urls, so if your proxy callback is plain HTTP that could also cause 
silent failures.

things to check:
- make sure your reverse proxy config is forwarding the full path (/callback) and not rewriting it
- make sure it's also passing through query parameters (?code=xxx&state=xxx)
- callback url in your spotify dashboard needs to match exactly what soulsync is configured with, including https

this isn't something i can fix on the soulsync side since the redirect never actually makes it through to the app properly. it's a proxy config thing.

**Comment by redbeardymcgee** [comment]
While I do understand it could be a configuration error on my end, there really isn't anything that stands out. Additionally, in the case that the error is related to reverse proxying, it would likely disappear if the callback routes were included on the same listen port instead of on 8888. To my knowledge, this is the underyling issue at hand and my reverse proxy is exposing it rather than being the root cause.

My reverse proxy is Caddy, with zero rewriting. All query parameters are passed through unadulterated, which can be witnessed at [my SearxNG instance](https://search.mcgee.red) where I have an equivalent reverse proxy directive (the only meaningful difference is whether it redirects to the SearxNG instance versus the SoulSync service), so I would be surprised to find that any of the params are being dropped by the reverse proxy. The callback URL matches in every location, and I have tried capturing & redirecting with or without the `/callback` path but the error persists. I don't experience this problem with any of my other dozens of services running on the same host behind the same Caddy.  Many of these services include API calls (to Spotify as well!), but do not require a separate callback redirect. For example, I have Navidrome connected to Spotify with no issue, but its callback url is the same as the root subdomain path (at `/` on the default listen port, not a separate listener).

Again, I do believe that I am likely to have made a mistake in my configuration, but I am relatively certain the issue is on the SoulSync side such that any configuration I use to fix it from my end is a hacky workaround for an error in SoulSync. The callback listener should be on the same port as the base http server, aligning with practically all other services utilizing callback urls. I don't mean to belittle your work on SoulSync in any way, and am very grateful for how it helps me automate and organize my music collection for offline listening. I have never seen this approach before to the callback url, so don't understand why it is necessary or expected.

Thank you for this app. I am looking forward to the further improvements you make!

**Comment by Nezreka** [comment]
SoulSync already has a callback handler on port 8008 (the main app port).  Just change your redirect URI in SoulSync settings and your Spotify dashboard to use 8008 instead of 8888, and your proxy should handle it like everything else. The 8888 listener is a standalone server that exists for direct/local use but isn't needed when you're behind a reverse proxy. Let me know if that fixes it.

**Comment by redbeardymcgee** [comment]
Oh that's great news! Is it necessary to also include the `/callback` path in that case?

**Comment by Nezreka** [comment]
Yeah you will still need that /callback included

**Comment by jarodsmk** [comment]
> > > Sounds like you guys may still be running old code. New rate limits have been stress tested hard. Def not useless yet
> > 
> > 
> > Installed SoulSync a day ago using `boulderbadgedad/soulsync:latest` - I see there's an update since, so benefit-of-the-doubt, will update and revert
> 
> How did the test go?

Morning!

I reconnected/authenticated Spotify, and immediately afterwards - ran a search for 2 artists. Those were successful and got responses from the Spotify API, displaying their albums.

Stepped away to grab a coffee and came back about 30 mins later, ran another search and sadly encountered the same:

```
🎤 Fetching discography for artist: {artist ID} (name: {artist Name}, spotify: True)
100.81.41.100 - - [26/Feb/2026 22:58:39] "GET /api/activity/toasts HTTP/1.1" 200 -
100.81.41.100 - - [26/Feb/2026 22:58:39] "GET /api/downloads/status HTTP/1.1" 200 -
Your application has reached a rate/request limit. Retry will occur after: 79923 s
```

I'm happy to revert to using Apple to be honest, better experience since that integration has no issues... The only benefit I would be missing out on is the playlist sync, but I'm not bothered by this

**Comment by Nezreka** [comment]
Lol im a derp. I was breaking every users spotify rate limits because of the spotify enrichment worker that ran in the background and matched literally everything in soulsync db to spotify over multiple api calls. every artist, album and track. it was on by default lol. no paused by default

**Comment by redbeardymcgee** [comment]
So I'm able to authenticate with Spotify directly without using the copy/paste url method, but the spotify oauth error persists. I don't know what else could be the issue on my end.

**Comment by redbeardymcgee** [comment]
`Mar 03 08:56:12 perseus soulsync[1091907]: 🔴 Spotify OAuth error: Unknown error`

This is the current error message I'm receiving.

**Comment by Nezreka** [comment]
hey so i dug into this more and found a few things.
                                                                                                                                
  first, the standalone callback server on port 8888 was processing literally every request that hit it — healthchecks, browser
  probes, whatever. any request without oauth params would log Spotify OAuth error: Unknown error which was super misleading.
  that's fixed now, it only responds to actual /callback requests.

  but the real fix for your setup — since you're behind caddy you shouldn't be using port 8888 at all. the main app on port 8008
   already handles callbacks at /callback. here's what you need to do:

  1. in soulsync settings, change your spotify redirect uri to https://yourdomain.com/callback (whatever your caddy domain is)  
  2. add that same exact url in your spotify developer dashboard as a redirect uri
  3. you don't need to expose port 8888 through caddy at all

  caddy already proxies to 8008 for everything else so the callback will just flow through the same way. spotify requires https 
  for non-localhost redirects which caddy gives you automatically.

  the auth page will also now detect if you're using a reverse proxy and guide you through this instead of showing the old "copy
   paste the url" instructions. pushed the update, lmk if that fixes it.

   please let me know

**Comment by redbeardymcgee** [comment]
Since you noted the callback listener on the default port, I had discarded the caddy config for port 8888. It has only been the following:
```
@soulsync host xxx.yyy.zzz
        handle @soulsync {
                reverse_proxy soulsync:8008
        }
```
Before that, I had tested various configurations that redirect to the 8888 listener at `/callback`, but it was discarded upon your prior not. My Spotify developer dashboard and SoulSync both are pointed at `https://xxx.yyy.zzz/callback` since then. I will grab the new update and monitor again.

**Comment by redbeardymcgee** [comment]
I'm still seeing the unknown error just seconds after starting the new container. I haven't even engaged with the frontend to do anything yet.

**Comment by chrishoage** [comment]
Looking at the code in https://github.com/spotipy-dev/spotipy/blob/master/spotipy/oauth2.py#L438-L469 it expects 

1. To be run in an environment where it can open a web browser 
2. To be fed a 127.0.0.1 address with a port where it spins up a web worker 
3. Critically if it can't extract a port from the redirect URL it falls back to interactive methods https://github.com/spotipy-dev/spotipy/blob/master/spotipy/oauth2.py#L438-L469

There doesn't appear to be a way to specify a redirect_url with out a port, which is why portless urls aren't working here. 

spotipy.oauth2 seems unsuitable for a headless application for this reason 

I'm not sure of a proper fix, but it would likely involve vendoring spotipy.oauth2 and modifying the code such that it always starts a web server like the tidal client, and separates out the redirect uri param 

This way the reverse proxy would proxy 8889 to /tidal/callback and 8888 to /spotify/callback 

Note: I haven't checked if this project uses an older version of spotipy but git blame says that section hasn't changed in at least a year

**Comment by redbeardymcgee** [comment]
I'm not sure this issue is valid anymore, since most of the Spotify support seems to have been dropped.
